export const SPOTLESS_STATUS_IS_CLEAN = 'IS CLEAN';
export const SPOTLESS_STATUS_DID_NOT_CONVERGE = 'DID NOT CONVERGE';
export const SPOTLESS_STATUS_IS_DIRTY = 'IS DIRTY';

export const SPOTLESS_STATUSES = [
  SPOTLESS_STATUS_DID_NOT_CONVERGE,
  SPOTLESS_STATUS_IS_CLEAN,
  SPOTLESS_STATUS_IS_DIRTY,
];
